console.log( 5 > 3 && 5==2 )
console.log (5 > 3 || 2 < 1)
console.log( "elton" == "elton" || 4 > 5 )
console.log( 3 == 3 && 4===4 )
console.log( ! (true && true) )
console.log(4 <= 4 && 5 <= 5)
console.log( 2 > 10 || 5 > 6)
console.log(! false && false)